export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: { Row: Profile; Insert: ProfileInsert; Update: ProfileUpdate; Relationships: [] };
      experiences: { Row: Experience; Insert: ExperienceInsert; Update: ExperienceUpdate; Relationships: [] };
      education: { Row: Education; Insert: EducationInsert; Update: EducationUpdate; Relationships: [] };
      skills: { Row: Skill; Insert: SkillInsert; Update: SkillUpdate; Relationships: [] };
      profile_certifications: { Row: ProfileCertification; Insert: ProfileCertificationInsert; Update: ProfileCertificationUpdate; Relationships: [] };
      profile_languages: { Row: ProfileLanguage; Insert: ProfileLanguageInsert; Update: ProfileLanguageUpdate; Relationships: [] };
      profile_links: { Row: ProfileLink; Insert: ProfileLinkInsert; Update: ProfileLinkUpdate; Relationships: [] };
      resumes: { Row: Resume; Insert: ResumeInsert; Update: ResumeUpdate; Relationships: [] };
      companies: { Row: Company; Insert: CompanyInsert; Update: CompanyUpdate; Relationships: [] };
      company_ratings: { Row: CompanyRating; Insert: CompanyRatingInsert; Update: CompanyRatingUpdate; Relationships: [] };
      employer_users: { Row: EmployerUser; Insert: EmployerUserInsert; Update: EmployerUserUpdate; Relationships: [] };
      jobs: { Row: Job; Insert: JobInsert; Update: JobUpdate; Relationships: [] };
      job_skills: { Row: JobSkill; Insert: JobSkillInsert; Update: JobSkillUpdate; Relationships: [] };
      applications: { Row: Application; Insert: ApplicationInsert; Update: ApplicationUpdate; Relationships: [] };
      saved_jobs: { Row: SavedJob; Insert: SavedJobInsert; Update: SavedJobUpdate; Relationships: [] };
      job_views: { Row: JobView; Insert: JobViewInsert; Update: JobViewUpdate; Relationships: [] };
      employer_plans: { Row: EmployerPlan; Insert: EmployerPlanInsert; Update: EmployerPlanUpdate; Relationships: [] };
      billing_orders: { Row: BillingOrder; Insert: BillingOrderInsert; Update: BillingOrderUpdate; Relationships: [] };
      billing_transactions: { Row: BillingTransaction; Insert: BillingTransactionInsert; Update: BillingTransactionUpdate; Relationships: [] };
      billing_events: { Row: BillingEvent; Insert: BillingEventInsert; Update: BillingEventUpdate; Relationships: [] };
      billing_entitlements: { Row: BillingEntitlement; Insert: BillingEntitlementInsert; Update: BillingEntitlementUpdate; Relationships: [] };
      billing_entitlement_usage: { Row: BillingEntitlementUsage; Insert: BillingEntitlementUsageInsert; Update: BillingEntitlementUsageUpdate; Relationships: [] };
    };
    Views: {
      company_rating_summaries: { Row: CompanyRatingSummary; Relationships: [] };
    } & Record<string, never>;
    Functions: {
      create_billing_order: { Args: { p_company_id: string; p_plan_id: string }; Returns: string };
      activate_billing_entitlement: { Args: { p_order_id: string }; Returns: string };
      can_create_job: { Args: { target_user_id?: string }; Returns: boolean };
      claim_company_owner: { Args: { target_company_id: string }; Returns: undefined };
      record_job_view: { Args: { target_job_id: string; target_viewer_key: string }; Returns: undefined };
      consume_job_posting_entitlement: { Args: Record<string, never>; Returns: undefined };
    };
    Enums: {
      user_type: 'job_seeker' | 'employer';
      application_status: 'applied' | 'viewed' | 'submitted' | 'reviewing' | 'shortlisted' | 'interview' | 'offer' | 'hired' | 'rejected';
    };
    CompositeTypes: Record<string, never>;
  };
};

type Timestamps = { created_at: string; updated_at: string };
type Profile = Timestamps & { id: string; full_name: string | null; first_name: string | null; last_name: string | null; email: string | null; phone: string | null; location: string | null; city: string | null; province: string | null; country: string | null; headline: string | null; professional_headline: string | null; bio: string | null; profile_photo_url: string | null; current_job_title: string | null; current_employer: string | null; years_experience: number | null; employment_status: string | null; desired_job_title: string | null; desired_employment_type: string | null; desired_work_arrangement: string | null; preferred_locations: string[] | null; expected_salary: number | null; availability: string; availability_start_date: string | null; user_type: Database['public']['Enums']['user_type'] | null; role_initialized: boolean; allow_employer_discovery: boolean };
type ProfileInsert = Partial<Omit<Profile, 'id' | 'created_at' | 'updated_at'>> & Pick<Profile, 'id'>;
type ProfileUpdate = Partial<Omit<Profile, 'id' | 'created_at' | 'updated_at'>>;
type Experience = Timestamps & { id: string; user_id: string; job_title: string; company_name: string; location: string | null; start_date: string; end_date: string | null; is_current: boolean; description: string | null };
type ExperienceInsert = Omit<Experience, 'id' | 'created_at' | 'updated_at'> & Partial<Pick<Experience, 'id'>>;
type ExperienceUpdate = Partial<Omit<Experience, 'id' | 'user_id' | 'created_at' | 'updated_at'>>;
type Education = Timestamps & { id: string; user_id: string; institution: string; degree: string | null; field_of_study: string | null; start_date: string | null; end_date: string | null; description: string | null };
type EducationInsert = Omit<Education, 'id' | 'created_at' | 'updated_at'> & Partial<Pick<Education, 'id'>>;
type EducationUpdate = Partial<Omit<Education, 'id' | 'user_id' | 'created_at' | 'updated_at'>>;
type Skill = Timestamps & { id: string; user_id: string; name: string; proficiency: string | null };
type SkillInsert = Omit<Skill, 'id' | 'created_at' | 'updated_at'> & Partial<Pick<Skill, 'id'>>;
type SkillUpdate = Partial<Omit<Skill, 'id' | 'user_id' | 'created_at' | 'updated_at'>>;
type ProfileCertification = Timestamps & { id: string; user_id: string; name: string; issuing_organization: string | null; issue_date: string | null; expiry_date: string | null; credential_id: string | null; credential_url: string | null };
type ProfileCertificationInsert = Omit<ProfileCertification, 'id' | 'created_at' | 'updated_at'> & Partial<Pick<ProfileCertification, 'id'>>;
type ProfileCertificationUpdate = Partial<Omit<ProfileCertification, 'id' | 'user_id' | 'created_at' | 'updated_at'>>;
type ProfileLanguage = Timestamps & { id: string; user_id: string; name: string; proficiency: string };
type ProfileLanguageInsert = Omit<ProfileLanguage, 'id' | 'created_at' | 'updated_at'> & Partial<Pick<ProfileLanguage, 'id'>>;
type ProfileLanguageUpdate = Partial<Omit<ProfileLanguage, 'id' | 'user_id' | 'created_at' | 'updated_at'>>;
type ProfileLink = Timestamps & { id: string; user_id: string; label: string; url: string };
type ProfileLinkInsert = Omit<ProfileLink, 'id' | 'created_at' | 'updated_at'> & Partial<Pick<ProfileLink, 'id'>>;
type ProfileLinkUpdate = Partial<Omit<ProfileLink, 'id' | 'user_id' | 'created_at' | 'updated_at'>>;
type Resume = Timestamps & { id: string; user_id: string; file_name: string; storage_path: string; file_path: string; file_url: string | null; is_primary: boolean; is_default: boolean };
type ResumeInsert = Omit<Resume, 'id' | 'created_at' | 'updated_at'> & Partial<Pick<Resume, 'id'>>;
type ResumeUpdate = Partial<Omit<Resume, 'id' | 'user_id' | 'created_at' | 'updated_at'>>;
type Company = Timestamps & { id: string; name: string; slug: string; description: string | null; website_url: string | null; website: string | null; industry: string | null; location: string | null; logo_url: string | null; facebook_url: string | null; instagram_url: string | null; linkedin_url: string | null; x_url: string | null; tiktok_url: string | null; youtube_url: string | null; created_by: string | null };
type CompanyInsert = Omit<Company, 'id' | 'created_at' | 'updated_at'> & Partial<Pick<Company, 'id'>>;
type CompanyUpdate = Partial<Omit<Company, 'id' | 'created_at' | 'updated_at'>>;
type CompanyRating = { id: string; company_id: string; user_id: string; rating: number; created_at: string; updated_at: string };
type CompanyRatingInsert = Omit<CompanyRating, 'id' | 'created_at' | 'updated_at'> & Partial<Pick<CompanyRating, 'id'>>;
type CompanyRatingUpdate = Partial<Pick<CompanyRating, 'rating'>>;
type CompanyRatingSummary = { company_id: string; average_rating: number; rating_count: number };
type EmployerUser = Timestamps & { company_id: string; user_id: string; role: string };
type EmployerUserInsert = Omit<EmployerUser, 'created_at' | 'updated_at'>;
type EmployerUserUpdate = Partial<Pick<EmployerUser, 'role'>>;
type Job = Timestamps & { id: string; company_id: string; title: string; slug: string; description: string; responsibilities: string[]; requirements: string[]; benefits: string[]; location: string; work_location: string; job_type: string; experience_level: string; salary_min: number | null; salary_max: number | null; salary_currency: string | null; status: string; published_at: string | null; expires_at: string | null; created_by: string | null };
type JobInsert = Omit<Job, 'id' | 'created_at' | 'updated_at'> & Partial<Pick<Job, 'id'>>;
type JobUpdate = Partial<Omit<Job, 'id' | 'company_id' | 'created_at' | 'updated_at'>>;
type JobSkill = { job_id: string; skill_id: string; created_at: string };
type JobSkillInsert = Omit<JobSkill, 'created_at'>;
type JobSkillUpdate = never;
type Application = Timestamps & { id: string; job_id: string; user_id: string; applicant_id: string; resume_id: string | null; cover_letter: string | null; status: Database['public']['Enums']['application_status']; notes: string | null };
type ApplicationInsert = Omit<Application, 'id' | 'created_at' | 'updated_at'> & Partial<Pick<Application, 'id'>>;
type ApplicationUpdate = Partial<Pick<Application, 'resume_id' | 'cover_letter' | 'status' | 'notes'>>;
type SavedJob = { user_id: string; job_id: string; created_at: string };
type SavedJobInsert = Omit<SavedJob, 'created_at'>;
type SavedJobUpdate = never;
type JobView = { job_id: string; viewer_key: string; viewed_at: string };
type JobViewInsert = JobView;
type JobViewUpdate = Partial<Pick<JobView, 'viewed_at'>>;
type BillingModel = 'one_time' | 'recurring';
type BillingOrderStatus = 'created' | 'pending' | 'paid' | 'failed' | 'cancelled' | 'expired' | 'refunded' | 'partially_refunded';
type BillingTransactionStatus = 'pending' | 'succeeded' | 'failed' | 'cancelled' | 'refunded' | 'partially_refunded';
type BillingProvider = 'payfast' | 'ozow';
type BillingEntitlementStatus = 'pending' | 'active' | 'exhausted' | 'expired' | 'revoked';
type EmployerPlan = Timestamps & { id: string; code: string; name: string; description: string; price: number; currency: string; billing_model: BillingModel; job_posting_allowance: number; active_job_limit: number | null; duration_days: number | null; is_active: boolean };
type EmployerPlanInsert = Omit<EmployerPlan, 'id' | 'created_at' | 'updated_at'> & Partial<Pick<EmployerPlan, 'id' | 'description' | 'price' | 'currency' | 'billing_model' | 'job_posting_allowance' | 'active_job_limit' | 'duration_days' | 'is_active'>>;
type EmployerPlanUpdate = Partial<Omit<EmployerPlan, 'id' | 'created_at' | 'updated_at'>>;
type BillingOrder = Timestamps & { id: string; company_id: string; plan_id: string; created_by_user_id: string | null; status: BillingOrderStatus; amount: number; currency: string; plan_snapshot: Json; checkout_url: string | null; expires_at: string | null; paid_at: string | null };
type BillingOrderInsert = Omit<BillingOrder, 'id' | 'created_at' | 'updated_at'> & Partial<Pick<BillingOrder, 'id' | 'created_by_user_id' | 'status' | 'currency' | 'plan_snapshot' | 'checkout_url' | 'expires_at' | 'paid_at'>>;
type BillingOrderUpdate = Partial<Pick<BillingOrder, 'status' | 'checkout_url' | 'expires_at' | 'paid_at'>>;
type BillingTransaction = Timestamps & { id: string; order_id: string; company_id: string; provider: BillingProvider; provider_transaction_id: string | null; provider_reference: string | null; provider_status: string | null; status: BillingTransactionStatus; amount: number; currency: string; failure_code: string | null; failure_message: string | null; paid_at: string | null; refunded_at: string | null };
type BillingTransactionInsert = Omit<BillingTransaction, 'id' | 'created_at' | 'updated_at'> & Partial<Pick<BillingTransaction, 'id' | 'provider_transaction_id' | 'provider_reference' | 'provider_status' | 'status' | 'currency' | 'failure_code' | 'failure_message' | 'paid_at' | 'refunded_at'>>;
type BillingTransactionUpdate = Partial<Pick<BillingTransaction, 'provider_transaction_id' | 'provider_reference' | 'provider_status' | 'status' | 'failure_code' | 'failure_message' | 'paid_at' | 'refunded_at'>>;
type BillingEvent = { id: string; provider: BillingProvider; provider_event_id: string; event_type: string; order_id: string | null; transaction_id: string | null; payload: Json; signature_verified: boolean; received_at: string; processed_at: string | null; processing_error: string | null; attempt_count: number };
type BillingEventInsert = Omit<BillingEvent, 'id' | 'received_at'> & Partial<Pick<BillingEvent, 'id' | 'received_at' | 'order_id' | 'transaction_id' | 'payload' | 'signature_verified' | 'processed_at' | 'processing_error' | 'attempt_count'>>;
type BillingEventUpdate = Partial<Pick<BillingEvent, 'order_id' | 'transaction_id' | 'payload' | 'signature_verified' | 'processed_at' | 'processing_error' | 'attempt_count'>>;
type BillingEntitlement = Timestamps & { id: string; company_id: string; order_id: string; plan_id: string; granted_quantity: number; consumed_quantity: number; active_job_limit: number | null; starts_at: string; expires_at: string | null; status: BillingEntitlementStatus };
type BillingEntitlementInsert = Omit<BillingEntitlement, 'id' | 'created_at' | 'updated_at'> & Partial<Pick<BillingEntitlement, 'id' | 'consumed_quantity' | 'active_job_limit' | 'starts_at' | 'expires_at' | 'status'>>;
type BillingEntitlementUpdate = Partial<Pick<BillingEntitlement, 'consumed_quantity' | 'active_job_limit' | 'expires_at' | 'status'>>;
type BillingEntitlementUsage = { id: string; entitlement_id: string; company_id: string; job_id: string; quantity: number; consumed_at: string; released_at: string | null };
type BillingEntitlementUsageInsert = Omit<BillingEntitlementUsage, 'id' | 'consumed_at'> & Partial<Pick<BillingEntitlementUsage, 'id' | 'consumed_at' | 'quantity' | 'released_at'>>;
type BillingEntitlementUsageUpdate = Partial<Pick<BillingEntitlementUsage, 'released_at'>>;
